### ISSUE TITLE
MS .NET error 299

### ISSUE THREAD

**Issue by My-BallsItch** [Fedoraware/Fedoraware#589]
**Fedoraware Version Date:[v1.6.2]**  

## Description:  

Microsoft .NET Error ["Only part of a ReadProcessMemory or WritepRocessMemory request was completed"]

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error
Reproducing:
Launch Fedoraloader with VAC bypass, error should appear when its currently "Starting Steam"

## Additional context 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at Fedoraloader.MainWindow.VacBypass()
   at Fedoraloader.MainWindow.GetGameProcess()
   at Fedoraloader.MainWindow.RunLoader()
   at Fedoraloader.MainWindow.<btnLoad_Click>b__7_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Fedoraloader.MainWindow.btnLoad_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by johnathon-walnut** [comment]
\>\>\>https://GitHub.com/LNX00/Fedoraloader
